### ISSUE TITLE
google.maps.... Types

### ISSUE THREAD

**Issue by thomi137** [xon52/v3-gmaps#14]
Hi. Sorry I have to contact you this way, but the link to your page is broken on GH.
I really really love this library (took me half a day now to move the vue 2 code from your Medium Post to vue 3 and saw that you were thinking along the same lines).

One issue I find in the doc (and also when I look through the source code). I would like to be able to access the google enum types they use (BOTTOM_LEFT, etc.). Either I did not see them or there is no way currently to access the api through this library.

Is that something outstanding? Am I missing something?. Would be glad to contribute btw.

Greets from Zurich
Thomas

**Comment by xon52** [comment]
Hey mate, no problem. Wasn't sure how many people were even using this so haven't developed it much (because I'm not really using it in an active project now either).

Are you wanting to use the Google enum types for something specific, or do you just want to access them?

I have created a PR which simply adds and exposes the type through so you could access it like so:
![image](https://user-images.githubusercontent.com/30713944/174403297-67fe63ac-9f49-48a4-8e1d-7eaf5be96c78.png)

But do you want the enum specifically or what?

**Comment by xon52** [comment]
Had a play and while you can access the Google Maps API, it doesn't have intellisense unless you also install `@types/google.maps` and then give the resolved `getAPI()` value the type `type of google.maps` which I didn't include.
(I can explain that a bit more if you're interested).

I have also updated the PR (#15) to export enums instead of types, so you would be able to do something like:
![image](https://user-images.githubusercontent.com/30713944/174414520-3271be34-77de-49c8-934f-f4c91d3f3571.png)

Is that more what you were thinking?

**Comment by xon52** [comment]
No reply but I merged the PR above anyway. Hope that helps.
