### ISSUE TITLE
"error" event on map

### ISSUE THREAD

**Issue by gerritvanaaken** [xon52/v3-gmaps#18]
When the map cannot be loaded, or the connection is slow, there is an error message, which is fine. But it would be even more flexible if you could also fire an "error" event to give me the opportunity to display a reload button or something similar.

**Comment by xon52** [comment]
Unfortunately I can only emit an `@error` event for Vue-related errors. When the Map won't load because of Google / API / API Key issues then as far as Vue knows, it has loaded. Next iteration of this I'll see if I can think of a better way to pass these errors into Vue.
But you should have an `@error` event now for the Map component in `v0.1.6`.

**Comment by gerritvanaaken** [comment]
Alright, let’s see! ;-)

A year ago, we forked your v2 Map.vue component and did a lot of changes to fit our needs. See the attached file. I don’t want to do the forking anymore, obviously...

Here the error message works pretty well for native GoogleMaps errors, especially for non-loading Maps. Maybe you can transfer this in an elegant way to the new version?

[Map.vue](https://github.com/xon52/v3-gmaps/files/9167181/Map.txt)

**Comment by xon52** [comment]
Awesome. I'll have a look at that when I get back to this 🙏
