### ISSUE TITLE
How to change Polygon options after first paint

### ISSUE THREAD

**Issue by gerritvanaaken** [xon52/v3-gmaps#19]
This might be connected to issue #16 – I want to change the thickness of Polygon stroke when I’m clicking on it. And decrease the thickness when a different polygon is clicked. 

My idea would be to create my own storage with the actual Google Maps Polygon Objects, but I need to build and maintain this storage, so @mounted and @unmounted events with the Object as payload would be handy for Polygons, too ;-)

**Comment by xon52** [comment]
I can't test I haven't broken everything as StackBlitz is broken because of `vue-router` issues, and condesandbox.io is not downloading the latest packages for some reason - but it all works on my machine 😬🙄 
`v0.1.6` should now have mounted and unmounted events for practically all the components which returns their respective 
 wrapped Google object.

**Comment by gerritvanaaken** [comment]
You’re amazing, will test this very soon!
